config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :admin do
    resources :orders
    resources :products do
      resources :stocks
    end
    resources :categories
  end
  devise_for :admins
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "home#index"

  authenticated :admin_user do
    root to: "admin#index",as: :admin_root
  end

  resources :categories, only: [:show] do
    collection do
      get 'search'
    end
  end
  resources :products,only: [:show]
  get "admin" => "admin#index"
  get "cart" => "carts#show"
  post "checkout" => "checkouts#create"
  get '/success', to: 'checkouts#success', as: 'success'
  get "cancel" => "checkouts#cancel"
  post "webhook" => "webhooks#stripe"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_one_attached :image

    has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_products
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :image
    belongs_to :category

    has_many :stocks, dependent: :destroy
    has_many :order_products

    before_create :generate_sku

  private

  def generate_sku
    loop do
      self.sku = SecureRandom.hex(5).upcase # Generating a random 5-character hexadecimal string
      break unless Product.exists?(sku: sku)
    end
  end
end
  

app/models/stock.rb
class Stock < ApplicationRecord
    belongs_to :product
end
  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    before_action :authenticate_admin!
    def index
        @orders = Order.where(fulfilled: false).order(created_at: :desc).take(5)
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def show
        
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @main_categories = Category.take(8)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def show
        @product =Product.find(params[:id])
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/webhooks_helper.rb
module WebhooksHelper
end

app/views/admin/index.html.erb
<div class="flex flex-col w-full">
    <h2 class="text-3xl mt-4 text-gray-800 mb-8 font-bold ">Unfullfilled Orders</h2>
    <div class="overflow-x-auto">
      <table class="min-w-full bg-gray-100" style="border-collapse: separate; border-spacing: 0;">
      <thead>
        <tr class="text-gray-800">
          <th class="px-6 py-3 border-b-2 border-gray-200 bg-gray-100">Order ID</th>
          <th class="px-6 py-3 border-b-2 border-gray-200 bg-gray-100">Customer</th>
          <th class="px-6 py-3 border-b-2 border-gray-200 bg-gray-100">Date</th>
          <th class="px-6 py-3 border-b-2 border-gray-200 bg-gray-100">Amount</th>
        </tr>
      </thead>
      <tbody class="text-gray-700">
        <% @orders.each do |order| %>
          <tr>
            <td class="px-6 py-4 border-b border-gray-200">
              <%= link_to order.id, admin_order_path(order), class: "underline" %>
            </td>
            <td class="px-6 py-4 border-b border-gray-200">
              <%= order.customer_email %>
            </td>
            <td class="px-6 py-4 border-b border-gray-200">
              <%= order.created_at.strftime("%B %d, %Y %H:%M") %>
            </td>
            <td class="px-6 py-4 border-b border-gray-200">
              <%= (order.total/100.0).to_s %>
            </td>
          </tr>
        <% end %>
      </tbody>
      </table>
    </div>
  </div>

app/views/shared/_anav.html.erb
<nav class="flex w-1/5">
    <div class="w-56 p-2 h-screen bg-gradient-to-b from-green-500 to-teal-500 fixed top-0">
        <div class="flex items-center justify-between">
            <h1 class="text-3xl font-semibold whitespace-nowrap font-pacifico text-white ml-6">
                Cartify
                <i class="fa-solid fa-cart-shopping"></i>
            </h1>
            
        </div>
        <h2 class="text-md py-2 px-12 text-white font-bold hidden md:block">Admin Page</h2>
        <ul class="mt-8">
            <li>
              <%= link_to admin_path, class: "block px-4 py-2 hover:bg-green-300 rounded text-white text-left flex items-center" do %>
                <%= image_tag("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 24 24' stroke-width='2' stroke='white' width='16' height='16' class='mr-2'%3E%3Cpath stroke-linecap='round' stroke-linejoin='round' d='M15.666 3.888A2.25 2.25 0 0 0 13.5 2.25h-3c-1.03 0-1.9.693-2.166 1.638m7.332 0c.055.194.084.4.084.612v0a.75.75 0 0 1-.75.75H9a.75.75 0 0 1-.75-.75v0c0-.212.03-.418.084-.612m7.332 0c.646.049 1.288.11 1.927.184 1.1.128 1.907 1.077 1.907 2.185V19.5a2.25 2.25 0 0 1-2.25 2.25H6.75A2.25 2.25 0 0 1 4.5 19.5V6.257c0-1.108.806-2.057 1.907-2.185a48.208 48.208 0 0 1 1.927-.184' /%3E%3C/svg%3E".html_safe, class: "inline-block align-middle") %>
                <span class="hidden md:inline-block ml-2">Dashboard</span>
              <% end %>
            </li>
            <li>
                <%= link_to admin_products_path,class:"block px-4 py-2 hover:bg-green-300 rounded text-white text-left" do%>
                    <i class="fa-brands fa-product-hunt"></i>
                    <span class="hidden md:inline-block">Products</span>
                <%end%>
            </li>
            <li>
                <%= link_to admin_categories_path,class:"block px-4 py-2 hover:bg-green-300 rounded text-white text-left" do%>
                    <i class="fa-solid fa-list"></i>
                    <span class="hidden md:inline-block">Categories</span>
                <%end%>
            </li>

            <li>
               <%= link_to admin_orders_path, class: "block px-4 py-2 hover:bg-green-300 rounded text-white text-left flex items-center" do %>
                    <i class="fa-solid fa-file-invoice-dollar"></i>
                    <span class="hidden md:inline-block ml-2">Order</span>
                <% end %>
            </li>

            <li>
                <%= link_to destroy_admin_session_path,data:{"turbo-method": :delete,"turbo-confirm":"Are you sure you wnat to logout?"},class:"block px-4 py-2 hover:bg-green-300 rounded text-white text-left" do%>
                    <i class="fa-solid fa-arrow-right-from-bracket"></i>
                    <span class="hidden md:inline-block">Sign Out</span>
                <%end%>
            </li>
        </ul>
    </div>
</nav>

app/views/shared/_footer.html.erb
<div class="container mx-auto py-2 bottom-0 w-full">
  <div class="flex flex-col items-center justify-center sm:flex-row ml-48">
    <p class="text-center font-body font-light text-primary dark:text-white sm:mr-auto sm:text-left ml-80">
      ©2020 Clarify. 
      <a href="/" class="ml-2">
        <i class="fa-solid fa-cart-shopping"></i>
      </a>
    </p>
  </div>
</div>

app/views/shared/_unavbar.html.erb
<nav class="fixed w-full top-0 bg-gradient-to-r from-blue-400 to-indigo-600 z-10 py-2">
    <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
        <div class="relative flex items-center justify-between h-14">
            <a href="/" class="flex items-center space-x-3">
                <span class="self-center text-3xl font-semibold whitespace-nowrap font-pacifico text-white ml-8">
                    Cartify
                    <i class="fa-solid fa-cart-shopping"></i>
                </span>
            </a>
            <%if user_signed_in?%>
                    <div class="flex items-center space-x-20"> <!-- Wrapped all icons in one div and added space-x-12 for horizontal spacing -->
                        <div class="ml-12">
                             <%= link_to edit_user_registration_path, class: "relative z-30 flex flex-col items-center  font-body text-sm font-medium text-primary transition-colors group-hover:text-green dark:text-white dark:group-hover:text-secondary" do %>
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" width="25" height="25"style="fill: white;"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M224 256A128 128 0 1 0 224 0a128 128 0 1 0 0 256zm-45.7 48C79.8 304 0 383.8 0 482.3C0 498.7 13.3 512 29.7 512H418.3c16.4 0 29.7-13.3 29.7-29.7C448 383.8 368.2 304 269.7 304H178.3z"/></svg>
                                
                            <% end %>
                        </div>

                        <div>
                           <%= link_to destroy_user_session_path, method: :delete, class: "relative z-30 flex flex-col items-center mr-8 ml-[-2.5rem] pr-[1.5rem] font-body text-sm font-medium text-primary transition-colors group-hover:text-green dark:text-white dark:group-hover:text-secondary", data: { turbo_confirm: 'Are you sure?', "turbo-method": :delete } do %>
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" width="25" height="25"style="fill: white;"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M502.6 278.6c12.5-12.5 12.5-32.8 0-45.3l-128-128c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3L402.7 224 192 224c-17.7 0-32 14.3-32 32s14.3 32 32 32l210.7 0-73.4 73.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0l128-128zM160 96c17.7 0 32-14.3 32-32s-14.3-32-32-32L96 32C43 32 0 75 0 128L0 384c0 53 43 96 96 96l64 0c17.7 0 32-14.3 32-32s-14.3-32-32-32l-64 0c-17.7 0-32-14.3-32-32l0-256c0-17.7 14.3-32 32-32l64 0z"/></svg>
                            <% end %>
                        </div>
                        <div>
                            <div class="hidden sm:flex sml:ml-6 mr-12 items-center justify-center absolute top-0 right-0 mr-4 mt-2">
                                <div class="flex space-x-10">
                                    <%= link_to cart_path,class: "text-white py-2 rounded-md text-md font-medium" do %>
                                        <i class="fa-solid fa-cart-plus text-3xl"></i>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    </div>
            <%else%>
                 <div class="flex items-center space-x-20"> <!-- Wrapped all icons in one div and added space-x-12 for horizontal spacing -->
                        <div class="ml-12">
                             <%= link_to new_user_registration_path, class: "relative z-30 flex flex-col items-center  font-body text-sm font-medium text-primary transition-colors group-hover:text-green dark:text-white dark:group-hover:text-secondary" do %>
                               <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512" style="fill: white;" class="w-6 h-6 inline-block mr-2">
                                    <path d="M96 128a128 128 0 1 1 256 0A128 128 0 1 1 96 128zM0 482.3C0 383.8 79.8 304 178.3 304h91.4C368.2 304 448 383.8 448 482.3c0 16.4-13.3 29.7-29.7 29.7H29.7C13.3 512 0 498.7 0 482.3zM504 312V248H440c-13.3 0-24-10.7-24-24s10.7-24 24-24h64V136c0-13.3 10.7-24 24-24s24 10.7 24 24v64h64c13.3 0 24 10.7 24 24s-10.7 24-24 24H552v64c0 13.3-10.7 24-24 24s-24-10.7-24-24z"/>
                                </svg>  
                            <% end %>
                        </div>

                        <div>
                           <%= link_to new_user_session_path, method: :delete, class: "relative z-30 flex flex-col items-center mr-8 ml-[-2.5rem] pr-[1.5rem] font-body text-sm font-medium text-primary transition-colors group-hover:text-green dark:text-white dark:group-hover:text-secondary" do %>
                                 <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" style="fill: white;" class="w-6 h-6 inline-block mr-2">
                                    <path d="M217.9 105.9L340.7 228.7c7.2 7.2 11.3 17.1 11.3 27.3s-4.1 20.1-11.3 27.3L217.9 406.1c-6.4 6.4-15 9.9-24 9.9c-18.7 0-33.9-15.2-33.9-33.9l0-62.1L32 320c-17.7 0-32-14.3-32-32l0-64c0-17.7 14.3-32 32-32l128 0 0-62.1c0-18.7 15.2-33.9 33.9-33.9c9 0 17.6 3.6 24 9.9zM352 416l64 0c17.7 0 32-14.3 32-32l0-256c0-17.7-14.3-32-32-32l-64 0c-17.7 0-32-14.3-32-32s14.3-32 32-32l64 0c53 0 96 43 96 96l0 256c0 53-43 96-96 96l-64 0c-17.7 0-32-14.3-32-32s14.3-32 32-32z"/>
                                </svg>
                            <% end %>
                        </div>
                </div>
            <%end%>
        </div>
    </div>
</nav>