config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :admin do
    resources :orders
    resources :products do
      resources :stocks
    end
    resources :categories
  end
  devise_for :admins
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "home#index"

  authenticated :admin_user do
    root to: "admin#index",as: :admin_root
  end

  resources :categories, only: [:show] do
    collection do
      get 'search'
    end
  end
  resources :products,only: [:show]
  get "admin" => "admin#index"
  get "cart" => "carts#show"
  post "checkout" => "checkouts#create"
  get '/success', to: 'checkouts#success', as: 'success'
  get "cancel" => "checkouts#cancel"
  post "webhook" => "webhooks#stripe"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_one_attached :image

    has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_products
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :image
    belongs_to :category

    has_many :stocks, dependent: :destroy
    has_many :order_products

    before_create :generate_sku

  private

  def generate_sku
    loop do
      self.sku = SecureRandom.hex(5).upcase # Generating a random 5-character hexadecimal string
      break unless Product.exists?(sku: sku)
    end
  end
end
  

app/models/stock.rb
class Stock < ApplicationRecord
    belongs_to :product
end
  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController
  before_action :set_admin_order, only: %i[ show edit update destroy ]

  # GET /admin/orders or /admin/orders.json
  def index
    @not_fulfilled_orders = Order.where(fulfilled: false).order(created_at: :asc)
    @fulfilled_orders = Order.where(fulfilled: true).order(created_at: :asc)
  end

  # GET /admin/orders/1 or /admin/orders/1.json
  def show
  end

  # GET /admin/orders/new
  def new
    @admin_order = Order.new
  end

  # GET /admin/orders/1/edit
  def edit
  end

  # POST /admin/orders or /admin/orders.json
  def create
    @admin_order = Order.new(admin_order_params)

    respond_to do |format|
      if @admin_order.save
        format.html { redirect_to admin_order_url(@admin_order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @admin_order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/orders/1 or /admin/orders/1.json
  def update
    respond_to do |format|
      if @admin_order.update(admin_order_params)
        format.html { redirect_to admin_order_url(@admin_order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @admin_order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/orders/1 or /admin/orders/1.json
  def destroy
    @admin_order.destroy!

    respond_to do |format|
      format.html { redirect_to admin_orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_order
      @admin_order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_order_params
      params.require(:order).permit(:customer_email, :fulfilled, :total, :address)
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    before_action :authenticate_admin!
    def index
        @orders = Order.where(fulfilled: false).order(created_at: :desc).take(5)
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def show
        
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @main_categories = Category.take(8)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def show
        @product =Product.find(params[:id])
    end
end

app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
    skip_forgery_protection

    def stripe
        secret_key = Rails.application.credentials.stripe[:secret_key]
        Stripe.api_key = secret_key

        payload = request.body.read
        sig_header = request.env["HTTP_STRIPE_SIGNATURE"]

        endpoint_secret = Rails.application.credentials.stripe[:webhook_secret]
        event = nil

        begin
          event = Stripe::Webhook.construct_event(payload, sig_header, endpoint_secret)
        rescue JSON::ParserError => e
          status 400
          return
        rescue Stripe::SignatureVerificationError => e
          puts "Webhook signature verification failed."
          status 400
          return
        end
    
        case event.type 
        when 'checkout.session.completed'
          session = event.data.object 
          shipping_details = session["shipping_details"]
          puts "Session: #{session}"
          if shipping_details
            address = "#{shipping_details['address']['line1']} #{shipping_details['address']['city']}, #{shipping_details['address']['state']} #{shipping_details["address"]["postal_code"]}"
          else
            address = ""
          end
          order = Order.create!(customer_email: session["customer_details"]["email"], total: session["amount_total"], address: address, fulfilled: false)
          puts "Order: #{order}"
          full_session = Stripe::Checkout::Session.retrieve({
            id: session.id,
            expand: ['line_items']
          }),
          line_items = full_session.line_items
          line_items["data"].each do |item|
            product = Stripe::Product.retrieve(item["price"]["product"])
            product_id = product["metadata"]["product_id"].to_i
            OrderProduct.create!(order: order, product_id: product_id, quantity: item["quantity"], size: product["metadata"]["size"])
            Stock.find(product["metadata"]["product_stock_id"]).decrement!(:amount, item["quantity"])
          end
        else
          puts "Unhandled event type: #{event.type}" 
        end
    
        render json: { message: 'success' }
      end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/webhooks_helper.rb
module WebhooksHelper
end

app/views/admin/orders/_form.html.erb
<%= form_with(model: [:admin, admin_order], class: "contents") do |form| %>
  <% if admin_order.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(admin_order.errors.count, "error") %> prohibited this admin_order from being saved:</h2>

      <ul>
        <% admin_order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :customer_email %>
    <%= form.text_field :customer_email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :fulfilled %>
    <%= form.check_box :fulfilled, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="my-5">
    <%= form.label :total %>
    <%= form.number_field :total, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :address %>
    <%= form.text_field :address, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/admin/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Customer email:</strong>
    <%= order.customer_email %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Fulfilled:</strong>
    <%= order.fulfilled %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Total:</strong>
    <%= order.total %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Address:</strong>
    <%= order.address %>
  </p>

  <% if order.order_products.any? %>
    <strong class="block font-medium mb-1">Products:</strong>
    <% order.order_products.each do |op| %>
      <%= op.product.name %> 
      <%= op.size %>
      <%= op.quantity %>
    <% end %>
  <% end %>

  <% if action_name != "show" %>
    <%= link_to "Show this order", [:admin, order], class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this order", edit_admin_order_path(order), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/admin/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form", admin_order: @admin_order %>

<br>

<div>
  <%= link_to "Show this order",[:admin, @admin_order] %> |
  <%= link_to "Back to orders", admin_orders_path %>
</div>

app/views/admin/orders/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center mb-8">
    <h1 class="font-bold text-4xl">Orders</h1>
    <%= link_to "New order", new_admin_order_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <h2>Unfulfilled Orders</h2>
  <div class="flex flex-col w-full">
    <div class="overlow-x-auto sm:mx-0.5 lg:mx-0.5">
      <div class="py-2 inline-block min-w-full">
        <div class="overlow-x-auto">
          <table class="min-w-full overflow-x-scroll">
            <thead class="bg-white border-b">
              <tr>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                  Order ID
                </th>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                  Customer Email
                </th>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                  Address
                </th>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                  Total 
                </th>
              </tr>
            </thead>
            <tbody>
              <% @not_fulfilled_orders.each do |o| %>
                <tr class="bg-gray-50 border-b">
                  <td class="px-6 py-4 whitepsace-nowrap tex-sm font-medium text-gray-800 underline">
                    <%= link_to o.id, [:admin, o], class: 'underline' %>
                  </td>
                  <td class="px-6 py-4 whitepsace-nowrap tex-sm font-medium text-gray-800">
                    <%= o.customer_email %>
                  </td>
                  <td class="px-6 py-4 whitepsace-nowrap tex-sm font-medium text-gray-800">
                    <%= o.address %>
                  </td>
                  <td class="px-6 py-4 whitepsace-nowrap tex-sm font-medium text-gray-800">
                    <%= o.total %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          
        </div>
      </div>
    </div>
  </div>

  <h2>Fulfilled Orders</h2>
  <div class="flex flex-col w-full">
    <div class="overlow-x-auto sm:mx-0.5 lg:mx-0.5">
      <div class="py-2 inline-block min-w-full">
        <div class="overlow-x-auto">
          <table class="min-w-full overflow-x-scroll">
            <thead class="bg-white border-b">
              <tr>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                  Order ID
                </th>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                  Customer Email
                </th>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                  Address
                </th>
                <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
                  Total 
                </th>
              </tr>
            </thead>
            <tbody>
              <% @fulfilled_orders.each do |o| %>
                <tr class="bg-gray-50 border-b">
                  <td class="px-6 py-4 whitepsace-nowrap tex-sm font-medium text-gray-800 underline">
                    <%= link_to o.id, [:admin, o], class: 'underline' %>
                  </td>
                  <td class="px-6 py-4 whitepsace-nowrap tex-sm font-medium text-gray-800">
                    <%= o.customer_email %>
                  </td>
                  <td class="px-6 py-4 whitepsace-nowrap tex-sm font-medium text-gray-800">
                    <%= o.address %>
                  </td>
                  <td class="px-6 py-4 whitepsace-nowrap tex-sm font-medium text-gray-800">
                    <%= o.total %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          
      </div>
    </div>
  </div>

</div>
 

</div>

app/views/admin/orders/new.html.erb
<h1>New order</h1>

<%= render "form", admin_order: @admin_order %>

<br>

<div>
  <%= link_to "Back to orders", admin_orders_path %>
</div>

app/views/admin/orders/show.html.erb
<div class="max-w-lg mx-auto mt-8 bg-gray-200 rounded-lg shadow-md overflow-hidden">
  <div class="px-6 py-4">
    <p class="text-green-500"><%= notice %></p>

    <%= render @admin_order %>

    <div class="mt-4 flex justify-between items-center">
      <%= link_to "Edit this order", edit_admin_order_path(@admin_order), class: "bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded-md mr-2" %>
      <%= link_to "Back to orders", admin_orders_path, class: "bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded-md mr-2" %>
      <%= button_to "Destroy this order", admin_order_path(@admin_order), method: :delete, data: { confirm: "Are you sure?" }, class: "bg-red-500 hover:bg-red-700 text-white py-2 px-4 rounded-md mr-2" %>
    </div>
  </div>
</div>