config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :admin do
    resources :orders
    resources :products do
      resources :stocks
    end
    resources :categories
  end
  devise_for :admins
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "home#index"

  authenticated :admin_user do
    root to: "admin#index",as: :admin_root
  end

  resources :categories, only: [:show] do
    collection do
      get 'search'
    end
  end
  resources :products,only: [:show]
  get "admin" => "admin#index"
  get "cart" => "carts#show"
  post "checkout" => "checkouts#create"
  get '/success', to: 'checkouts#success', as: 'success'
  get "cancel" => "checkouts#cancel"
  post "webhook" => "webhooks#stripe"
end

app/models/category.rb
class Category < ApplicationRecord
    has_one_attached :image

    has_many :products
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  before_action :set_admin_category, only: %i[ show edit update destroy ]

  # GET /admin/categories or /admin/categories.json
  def index
    @admin_categories = Category.all
  end

  # GET /admin/categories/1 or /admin/categories/1.json
  def show
  end

  # GET /admin/categories/new
  def new
    @admin_category = Category.new
  end

  # GET /admin/categories/1/edit
  def edit
  end

  # POST /admin/categories or /admin/categories.json
  def create
    @admin_category = Category.new(admin_category_params)

    respond_to do |format|
      if @admin_category.save
        format.html { redirect_to admin_category_url(@admin_category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @admin_category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/categories/1 or /admin/categories/1.json
  def update
    respond_to do |format|
      if @admin_category.update(admin_category_params)
        format.html { redirect_to admin_category_url(@admin_category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @admin_category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/categories/1 or /admin/categories/1.json
  def destroy
    @admin_category.destroy!

    respond_to do |format|
      format.html { redirect_to admin_categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_category
      @admin_category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_category_params
      params.require(:category).permit(:name, :description,:image)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def show
        @category = Category.find(params[:id])
        @products = @category.products
    end
    
  def search
    @query = params[:query]
    @category = Category.find_by(name: @query)
    if @category
      redirect_to category_path(@category)
    else
      flash[:notice] = "Category not found"
      redirect_back fallback_location: root_path
    end
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <%= image_tag category.image if category.image.attached? %>
  <p class="my-5">
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p class="my-5">
    <strong>Description:</strong>
    <%= category.description %>
  </p>

  <% if action_name!="show"%>
   <%= link_to "Show this Category",[:admin,category],class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"%>
   <%= link_to "Edit this Category",edit_admin_category_path(category),class:"rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"%>
    <hr class="mt-6">
  <%end%>

</div>

app/views/admin/categories/_form.html.erb
<%= form_with(model: [:admin ,admin_category],class: "contents") do |form| %>
  <% if admin_category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(admin_category.errors.count, "error") %> prohibited this admin_category from being saved:</h2>

      <ul>
        <% admin_category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.submit%>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<div class="max-w-lg mx-auto mt-8 p-6 bg-green-200 rounded-lg shadow-md">
    <h1 class="text-2xl font-bold mb-4">Editing Category</h1>

    <%= render "form", admin_category: @admin_category %>

    <div class="mt-8 flex items-center">
        <%= link_to "Show", [:admin, @admin_category], class: "btn-secondary mr-4" %>
        <%= link_to "Back to categories", admin_categories_path, class: "btn-secondary" %>
    </div>
</div>

app/views/admin/categories/index.html.erb
<div class="w-full">
  <%if notice.present?%>
    <p style="color: green"><%= notice %></p>
  <%end%>
  <div class="flex justify-between items-center mt-5">
    <h1 class="font-bold text-4xl mb-4">Categories</h1>
    <%= link_to "New category", new_admin_category_path,class:"rounded-lg py-3 px-5 bg-blue-600 text-white block fonnt-medium" %>
  </div>
</div>
<div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-6 px-2 mb-4 pt-12">
  <% @admin_categories.each do |category|%>
  <div class="border border-purple-200 p-4 rounded-lg  hover:shadow-lg hover:shadow-pink-400 transition duration-300 transform hover:scale-110 mb-4">
      <%= image_tag category.image if category.image.attached? %>
      <%= link_to admin_category_path(category), class: "text-center block font-body text-lg font-semibold text-primary transition-colors hover:text-green dark:text-white dark:hover:text-secondary" do %>
        <%= category.name%>
      <% end %>
  </div>
  <%end%>
</div>

app/views/admin/categories/new.html.erb
<h1>New category</h1>

<%= render "form", admin_category: @admin_category %>

<br>

<div>
  <%= link_to "Back to categories", admin_categories_path %>
</div>

app/views/admin/categories/show.html.erb
<div class="max-w-md mx-auto mt-8 p-6 bg-green-200 rounded-lg">
    <p class="text-green-600"><%= notice %></p>

    <%= render @admin_category %>

    <div class="mt-4 flex items-center justify-between">
        <%= link_to "Edit", edit_admin_category_path(@admin_category), class: "text-indigo-600 hover:text-indigo-800" %> |
        <%= link_to "Back to categories", admin_categories_path, class: "text-indigo-600 hover:text-indigo-800" %> |
        <%= link_to "Destroy", admin_category_path(@admin_category), method: :delete, data: { turbo_confirm: 'Are you sure?', "turbo-method": :delete }, class: "text-red-600 hover:text-red-800" %>
    </div>
</div>