config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :admin do
    resources :orders
    resources :products do
      resources :stocks
    end
    resources :categories
  end
  devise_for :admins
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "home#index"

  authenticated :admin_user do
    root to: "admin#index",as: :admin_root
  end

  resources :categories, only: [:show] do
    collection do
      get 'search'
    end
  end
  resources :products,only: [:show]
  get "admin" => "admin#index"
  get "cart" => "carts#show"
  post "checkout" => "checkouts#create"
  get '/success', to: 'checkouts#success', as: 'success'
  get "cancel" => "checkouts#cancel"
  post "webhook" => "webhooks#stripe"
end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :image
    belongs_to :category

    has_many :stocks, dependent: :destroy
    has_many :order_products

    before_create :generate_sku

  private

  def generate_sku
    loop do
      self.sku = SecureRandom.hex(5).upcase # Generating a random 5-character hexadecimal string
      break unless Product.exists?(sku: sku)
    end
  end
end
  

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  before_action :set_admin_product, only: %i[ show edit update destroy ]

  # GET /admin/products or /admin/products.json
  def index
    @admin_products = Product.all
  end

  # GET /admin/products/1 or /admin/products/1.json
  def show
  end

  # GET /admin/products/new
  def new
    @admin_product = Product.new
  end

  # GET /admin/products/1/edit
  def edit
  end

  # POST /admin/products or /admin/products.json
  def create
    @admin_product = Product.new(admin_product_params)

    respond_to do |format|
      if @admin_product.save
        format.html { redirect_to admin_product_url(@admin_product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @admin_product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/products/1 or /admin/products/1.json
  def update
    respond_to do |format|
      if @admin_product.update(admin_product_params)
        format.html { redirect_to admin_product_url(@admin_product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @admin_product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/products/1 or /admin/products/1.json
  def destroy
    @admin_product.destroy!

    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_product
      @admin_product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_product_params
      params.require(:product).permit(:name, :description, :price, :category_id, :active, :image, :sku)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def show
        @product =Product.find(params[:id])
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_with(model: [:admin, admin_product], class: "contents") do |form| %>
  <% if admin_product.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(admin_product.errors.count, "error") %> prohibited this admin_product from being saved:</h2>

      <ul>
        <% admin_product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <% if admin_product.persisted? && admin_product.image.attached? %>
  <%= image_tag url_for(admin_product.image), class: "w-20 h-20 object-cover rounded-md" %>
<% end %>


    <%= form.label :image %>
    <%= form.file_field :image, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.number_field :price, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.order(:name), :id, :name, id: "category", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :active %>
    <%= form.check_box :active, class: "block mt-2 h-5 w-5" %>
  </div>

  <% unless admin_product.new_record? %>
    <div class="my-5">
      <%= link_to "Product Stock", admin_product_stocks_path(admin_product), class: "underline" %>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/admin/products/_product.html.erb
<div id="<%= dom_id product %>">

 <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>
  <% if product.image.attached? %>
    <%= image_tag url_for(product.image), class: "product-image" %>
  <% end %>

 

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= product.category.name %>
  </p>

  <p>
    <strong>Active:</strong>
    <%= product.active ? 'Yes' : 'No' %>
  </p>
  
  <% unless action_name == "show" %>
    <%= link_to "Show this product", [:admin, product] %>
    <%= link_to "Edit", edit_admin_product_path(product) %>
  <% end %>
</div>

app/views/admin/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", admin_product: @admin_product %>

<br>

<div>
  <%= link_to "Show this product", admin_product_path(@admin_product) %>
  |
  <%= link_to "Back to products", admin_products_path %>
</div>

app/views/admin/products/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="w-full">
  <%if notice.present?%>
    <p style="color: green"><%= notice %></p>
  <%end%>
  <div class="flex justify-between items-center mt-5">
    <h1 class="font-bold text-4xl mb-4">Products</h1>
    <%= link_to "New Product", new_admin_product_path,class:"rounded-lg py-3 px-5 bg-blue-600 text-white block fonnt-medium" %>
  </div>
</div>
<div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-6 px-2 mb-4 pt-12">
  <% @admin_products.each do |product|%>
  <div class="border border-purple-200 p-4 rounded-lg  hover:shadow-lg hover:shadow-pink-400 transition duration-300 transform hover:scale-110 mb-4">
      <%= image_tag product.image if product.image.attached? %>
      <%= link_to admin_product_path(product), class: "text-center block font-body text-lg font-semibold text-primary transition-colors hover:text-green dark:text-white dark:hover:text-secondary" do %>
        <%= product.name%>
      <% end %>
      Price: <%= product.price%>
  </div>
  <%end%>
</div>

app/views/admin/products/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New product</h1>

  <%= render "form", admin_product: @admin_product %>

  <%= link_to "Back to products", admin_products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/products/show.html.erb
<div class="container mx-auto">
  <div class="my-8">
    <p class="text-green-600"><%= notice %></p>
  </div>

  <div class="bg-white shadow-md rounded-md p-6 mb-8">
    <%= render @admin_product %>
  </div>

  <div class="flex items-center justify-between mb-4">
    <%= link_to "Edit this product", edit_admin_product_path(@admin_product), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
    <%= link_to "Back to products", admin_products_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>

    <%= button_to "Destroy this product", admin_product_path(@admin_product), method: :delete, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" %>
  </div>
</div>